dnd-side-project/dnd-10th-6-backend

src/main/java/com/dnd/namuiwiki/config/WebConfiguration.java

it closes #7 
cors 관련 설정 추가하였습니다.
- `WebConfiguration` 클래스 추가되었습니다.
- `application-loca.yml` 변경되었습니다.

feat: WebMvcConfiguration에 cors 관련 설정 추가(#7)

---

build.gradle
src/main/java/com/dnd/namuiwiki/jwt/JwtFilter.java
src/main/java/com/dnd/namuiwiki/jwt/JwtProvider.java
src/main/java/com/dnd/namuiwiki/jwt/JwtService.java
src/main/java/com/dnd/namuiwiki/jwt/LoginResponseDto.java
src/main/java/com/dnd/namuiwiki/jwt/TokenUserInfoDto.java
src/main/java/com/dnd/namuiwiki/presentation/auth/AuthController.java
src/main/java/com/dnd/namuiwiki/presentation/auth/dto/OAuthLoginResponse.java
src/main/java/com/dnd/namuiwiki/user/User.java
src/main/java/com/dnd/namuiwiki/user/UserRepository.java
src/main/java/com/dnd/namuiwiki/user/UserService.java
src/test/java/com/dnd/namuiwiki/jwt/JwtProviderTest.java

Spring Security 적용을 고민하다가 우선 제외하고 구현했습니다.
1. JwtProvider로 토큰 발행 및 검증
- OAuthProvider, OAuthId로 claim 생성
2. JwtFilter 적용
- permittedURIs로 필터 예외 경로 지정
- application-local.yml 업데이트 했습니다.
- claim에서 얻은 정보를 어떻게 관리해야할지 고민중인데, 혹시 좋은 방법이 있을까요?
- refresh는 금방 마무리해두겠습니다..ㅜ

JWT 토큰 인증 구현(refresh 진행중)

---

build.gradle

스웨거 설정하였습니다.
아래 url로 접속할 수 있습니다.
```
http://localhost:8080/swagger-ui/index.html
```
- application-local.yml 수정되었습니다.

spring docs openapi 스웨거 설정

---

k8s/configmap.yaml
k8s/deployment.yaml

configmap으로 application.yaml 주입(#21)

infra: configmap으로 application.yaml 주입

---

src/main/java/com/dnd/namuiwiki/domain/user/UserService.java
src/main/java/com/dnd/namuiwiki/domain/user/entity/User.java

bug: User 생성자 수정(#24)

---

.github/workflows/ci.yml
src/main/java/com/dnd/namuiwiki/common/dto/ResponseDto.java
src/main/java/com/dnd/namuiwiki/common/exception/ApplicationErrorException.java
src/main/java/com/dnd/namuiwiki/common/exception/ApplicationErrorType.java
src/main/java/com/dnd/namuiwiki/common/exception/GlobalExceptionHandler.java
src/main/java/com/dnd/namuiwiki/domain/auth/AuthController.java
src/main/java/com/dnd/namuiwiki/domain/auth/dto/SignUpRequest.java
src/main/java/com/dnd/namuiwiki/domain/auth/dto/SignUpResponse.java
src/main/java/com/dnd/namuiwiki/domain/jwt/JwtService.java
src/main/java/com/dnd/namuiwiki/domain/jwt/dto/TokenPairDto.java
src/main/java/com/dnd/namuiwiki/domain/oauth/OAuthProviderService.java
src/main/java/com/dnd/namuiwiki/domain/oauth/OAuthService.java
src/main/java/com/dnd/namuiwiki/domain/oauth/dto/OAuthUserInfoDto.java
src/main/java/com/dnd/namuiwiki/domain/oauth/kakao/OAuthKakaoService.java
src/main/java/com/dnd/namuiwiki/domain/user/UserRepository.java
src/main/java/com/dnd/namuiwiki/domain/user/UserService.java
src/main/java/com/dnd/namuiwiki/domain/user/entity/User.java

/login
- 기존 유저라면 accessToken과 refreshToken 응답
- 신규 가입 유저라면 HTTP status 404 코드와 함께 쿠키로 kakao oauth accessToken을 설정하여 응답
/signup
- 유저가 입력한 닉네임과 set-cookie로 설정된 쿠키와 함께 요청
- 회원가입 완료 후 accessToken과 refreshToken 응답

수정된 로그인 및 회원가입 플로우 구현

---

src/main/java/com/dnd/namuiwiki/common/converter/EnumConverterFactory.java
src/main/java/com/dnd/namuiwiki/config/WebConfiguration.java
src/main/java/com/dnd/namuiwiki/domain/dashboard/DashboardController.java
src/main/java/com/dnd/namuiwiki/domain/dashboard/DashboardRepository.java
src/main/java/com/dnd/namuiwiki/domain/dashboard/DashboardService.java
src/main/java/com/dnd/namuiwiki/domain/dashboard/model/BestWorthDashboardComponent.java
src/main/java/com/dnd/namuiwiki/domain/dashboard/model/CharacterDashboardComponent.java
src/main/java/com/dnd/namuiwiki/domain/dashboard/model/DashboardComponent.java
src/main/java/com/dnd/namuiwiki/domain/dashboard/model/HappyDashboardComponent.java
src/main/java/com/dnd/namuiwiki/domain/dashboard/model/MoneyDashboardComponent.java
src/main/java/com/dnd/namuiwiki/domain/dashboard/model/SadDashboardComponent.java
src/main/java/com/dnd/namuiwiki/domain/dashboard/model/dto/DashboardDto.java
src/main/java/com/dnd/namuiwiki/domain/dashboard/model/dto/GetDashboardRequest.java
src/main/java/com/dnd/namuiwiki/domain/dashboard/model/dto/RatioDto.java
src/main/java/com/dnd/namuiwiki/domain/dashboard/model/entity/Dashboard.java
src/main/java/com/dnd/namuiwiki/domain/option/OptionRepository.java
src/main/java/com/dnd/namuiwiki/domain/statistic/StatisticsService.java
src/main/java/com/dnd/namuiwiki/domain/statistic/model/Legend.java
src/main/java/com/dnd/namuiwiki/domain/statistic/model/RatioStatistic.java
src/main/java/com/dnd/namuiwiki/domain/statistic/model/Statistics.java
src/main/java/com/dnd/namuiwiki/domain/statistic/model/entity/Dashboard.java
src/main/resources/json/base-document.json

대시 보드 조회 API

---

src/main/java/com/dnd/namuiwiki/domain/dashboard/model/BestWorthDashboardComponent.java
src/main/java/com/dnd/namuiwiki/domain/dashboard/model/HappyDashboardComponent.java
src/main/java/com/dnd/namuiwiki/domain/dashboard/model/MoneyDashboardComponent.java
src/main/java/com/dnd/namuiwiki/domain/dashboard/model/SadDashboardComponent.java
src/main/java/com/dnd/namuiwiki/domain/survey/SurveyService.java

서버 jdk 17에 맞춰 메소드 변경합니다.
getFirst() -> get()

fix: getFirst를 get 메소드로 변경(#41)

---

src/main/java/com/dnd/namuiwiki/domain/survey/SurveyRepository.java
src/main/java/com/dnd/namuiwiki/domain/user/UserController.java
src/main/java/com/dnd/namuiwiki/domain/user/UserService.java
src/main/java/com/dnd/namuiwiki/domain/user/dto/EditUserProfileRequest.java
src/main/java/com/dnd/namuiwiki/domain/user/dto/UserProfileDto.java
src/main/java/com/dnd/namuiwiki/domain/user/entity/User.java

사용자 프로필 조회 및 수정 api 구현
- `GET` 사용자 프로필 조회 api #39 
- `PUT` 사용자 프로필 수정 api #44 
필요하다고 하셔서 먼저 개발했습니다. 
간단한 내용이라 #39 를 close 하고, 이 PR로 합치겠습니다.

사용자 프로필 조회 및 수정 api 구현

---

src/main/resources/json/base-document.json

it closes #56 .
MOULTI_CHOICE에 옵션에 MANUAL 옵션 추가했습니다.

MOULTI_CHOICE에 옵션에 MANUAL 옵션 추가(#56)

---

src/main/java/com/dnd/namuiwiki/common/model/BaseTimeEntity.java
src/main/java/com/dnd/namuiwiki/config/MongoConfiguration.java
src/main/java/com/dnd/namuiwiki/domain/dashboard/model/entity/Dashboard.java
src/main/java/com/dnd/namuiwiki/domain/option/entity/Option.java
src/main/java/com/dnd/namuiwiki/domain/question/entity/Question.java
src/main/java/com/dnd/namuiwiki/domain/survey/model/entity/Survey.java
src/main/java/com/dnd/namuiwiki/domain/user/entity/User.java

it closes #33 .
모든 Entity에 createdAt, updatedAt 필드 추가
- `BaseTimeEntity` 클래스 정의한 후 Entity에서 상속받았습니다.

모든 Entity에 createdAt, updatedAt 필드 추가(#33)

---

.github/workflows/ci.yml
src/main/java/com/dnd/namuiwiki/common/filter/JwtExceptionHandlerFilter.java
src/main/java/com/dnd/namuiwiki/config/FilterConfiguration.java

spring.cors.allowed-origins의 값들을 response의 Access-Control-Allow-Origin 헤더에 추가했습니다.

JwtExceptionHandlerFilter에서 CORS 설정(#54)

---

src/main/java/com/dnd/namuiwiki/common/exception/ApplicationErrorType.java
src/main/java/com/dnd/namuiwiki/domain/survey/AnswerController.java
src/main/java/com/dnd/namuiwiki/domain/survey/SurveyRepository.java
src/main/java/com/dnd/namuiwiki/domain/survey/SurveyService.java
src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/GetAnswersByQuestionResponse.java
src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/SingleAnswerWithSurveyDetailDto.java
src/main/java/com/dnd/namuiwiki/domain/survey/type/Period.java
src/main/java/com/dnd/namuiwiki/domain/survey/type/Relation.java
src/test/java/com/dnd/namuiwiki/domain/survey/SurveyServiceTest.java

질문별 상세보기 API
- 필터 구현을 위해서 Period, Relation에 각각 TOTAL enum을 추가했습니다.
- projection 적용은 추후 구현
- createdAt, updatedAt 추가되면 response에 작성 일자 포함해야 함

질문별 상세보기 API(#48)

---

src/main/java/com/dnd/namuiwiki/common/exception/ApplicationErrorType.java
src/main/java/com/dnd/namuiwiki/domain/question/QuestionService.java
src/main/java/com/dnd/namuiwiki/domain/question/dto/QuestionDto.java
src/main/java/com/dnd/namuiwiki/domain/question/entity/Question.java
src/main/java/com/dnd/namuiwiki/domain/survey/model/SurveyAnswer.java
src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/AnswerDto.java
src/main/resources/json/base-document.json

Question에 reasonRequired 필드 추가되었습니다.
- Question에 reasonRequired boolean 필드 추가
- 문항 조회 시 reasonRequired 함께 응답
- 설문 생성 시 reasonReqruied가 true인 답변에 이유 없을 경우 에러 처리

Question에 reasonRequired 필드 추가

---

src/main/java/com/dnd/namuiwiki/common/dto/PageableDto.java
src/main/java/com/dnd/namuiwiki/domain/survey/SurveyController.java
src/main/java/com/dnd/namuiwiki/domain/survey/SurveyService.java
src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/ReceivedSurveyDto.java

내가 받은 설문 조회 API 구현하였습니다.
- 내가 받은 설문 조회 api 추가
`PageableDto`를 일단 추가해두었는데, #53 이 머지되면 해당 커밋 revert하고 rebase하겠습니다.

feat: 내가 받은 설문 조회 API (#70)

---

src/main/java/com/dnd/namuiwiki/domain/survey/SurveyService.java
src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/SingleAnswerWithSurveyDetailDto.java

질문별 상세보기 응답에 작성일자 포함

---

src/main/java/com/dnd/namuiwiki/domain/survey/SurveyRepository.java
src/main/java/com/dnd/namuiwiki/domain/survey/SurveyService.java
src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/CreateSurveyRequest.java
src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/SentSurveyDto.java
src/main/java/com/dnd/namuiwiki/domain/user/UserController.java

내가 작성한 설문 목록 조회 API

---

src/main/java/com/dnd/namuiwiki/common/exception/ApplicationErrorType.java
src/main/java/com/dnd/namuiwiki/domain/question/type/QuestionName.java
src/main/java/com/dnd/namuiwiki/domain/survey/model/SurveyAnswer.java

feat: 빌릴 수 있는 액수 범위 설정(#75)

---

src/main/java/com/dnd/namuiwiki/domain/survey/SurveyController.java
src/main/java/com/dnd/namuiwiki/domain/survey/SurveyService.java
src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/GetSurveyResponse.java

feat: 설문별 상세보기 API 구현(#49)

---

src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/GetSurveyResponse.java

설문 상세보기 응답에 text, value 추가

---

src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/GetSurveyResponse.java

fix: 설문 상세 조회 응답에 option value 포함(#83)

---

src/main/java/com/dnd/namuiwiki/domain/survey/SurveyService.java

bug: access token empty 확인

---

src/main/java/com/dnd/namuiwiki/domain/dashboard/model/BestWorthDashboardComponent.java
src/main/java/com/dnd/namuiwiki/domain/dashboard/model/HappyDashboardComponent.java
src/main/java/com/dnd/namuiwiki/domain/dashboard/model/SadDashboardComponent.java

대시보드에서 totalCount 0인 경우 percentage 0으로 처리

---

src/main/java/com/dnd/namuiwiki/config/AsyncConfiguration.java
src/main/java/com/dnd/namuiwiki/domain/statistic/StatisticsService.java

설문 작성 시 통계 작업 비동기 처리

---

src/main/java/com/dnd/namuiwiki/domain/dashboard/DashboardService.java
src/main/java/com/dnd/namuiwiki/domain/dashboard/model/BestWorthDashboardComponent.java
src/main/java/com/dnd/namuiwiki/domain/dashboard/model/CharacterDashboardComponent.java
src/main/java/com/dnd/namuiwiki/domain/dashboard/model/DashboardComponent.java
src/main/java/com/dnd/namuiwiki/domain/dashboard/model/HappyDashboardComponent.java
src/main/java/com/dnd/namuiwiki/domain/dashboard/model/MoneyDashboardComponent.java
src/main/java/com/dnd/namuiwiki/domain/dashboard/model/SadDashboardComponent.java

feat: 대시보드 응답에 questionId 추가

---

src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/GetSurveyResponse.java

Question 순서 정합성 오류 수정

---

src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/GetSurveyResponse.java

release 0.0.7

---

build.gradle

모니터링을 위해 actuator, micrometer 추가

---

src/main/java/com/dnd/namuiwiki/domain/survey/SurveyRepository.java
src/main/java/com/dnd/namuiwiki/domain/survey/SurveyService.java
src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/SentSurveyDto.java

내가 작성한 설문 목록 오류 수정

---

src/main/java/com/dnd/namuiwiki/domain/statistic/model/RatioStatistic.java

it closes #105
fix: 직접입력일 경우에도 counting 하도록 수정(#105)

직접입력일 경우에도 counting 하도록 수정(#105)

---

src/main/java/com/dnd/namuiwiki/domain/statistic/model/RatioStatistic.java

release v0.2.3

---

src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/GetSurveyResponse.java

설문 단일 조회 시 questionName 필드 추가(#122)
`SingleQuestionAndAnswer`에 `questionName` 필드 추가되었습니다.

feat: 설문 단일 조회 시 questionName 필드 추가(#122)

---

src/main/java/com/dnd/namuiwiki/domain/survey/SurveyService.java
src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/GetAnswersByQuestionResponse.java

질문별 상세보기 questionName 필드 추가(#129)

---

src/main/java/com/dnd/namuiwiki/domain/option/entity/Option.java
src/main/java/com/dnd/namuiwiki/domain/survey/SurveyService.java
src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/GetSurveyResponse.java
src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/SingleAnswerWithSurveyDetailDto.java

설문 조회 응답에 optionName 필드 추가
DB options 컬렉션에 `name` 필드 추가해야 합니다.

설문 조회 응답에 optionName 필드 추가(#133)

---

src/main/java/com/dnd/namuiwiki/domain/survey/SurveyService.java
src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/SingleAnswerWithSurveyDetailDto.java

feat: 질문이 NUMERIC 타입일 경우, 답변을 정수로 응답(#136)
기존 `String`으로 변환하는 메소드를 `Object`로 변경하였습니다.

feat: 질문이 NUMERIC 타입일 경우, 답변을 정수로 응답(#136)

---

src/main/java/com/dnd/namuiwiki/domain/dashboard/model/BestWorthDashboardComponent.java
src/main/java/com/dnd/namuiwiki/domain/dashboard/model/HappyDashboardComponent.java
src/main/java/com/dnd/namuiwiki/domain/dashboard/model/SadDashboardComponent.java

fix: 0일 경우 나누기 예외처리(#136)

---

src/main/java/com/dnd/namuiwiki/config/CacheConfiguration.java
src/main/java/com/dnd/namuiwiki/domain/question/QuestionRepository.java
src/main/java/com/dnd/namuiwiki/domain/question/entity/Question.java
src/main/java/com/dnd/namuiwiki/domain/survey/model/entity/Survey.java

#117 의 새로운 작업입니다.
Question Repository 메소드 캐싱 추가하였습니다.
- SimpleCacheManager 등록
- QuestionRepository의 메소드에 `@Cachable` 적용

Question Repository 메소드 캐싱(#98)

---

src/main/java/com/dnd/namuiwiki/common/exception/ApplicationErrorType.java
src/main/java/com/dnd/namuiwiki/domain/survey/SurveyController.java
src/main/java/com/dnd/namuiwiki/domain/survey/SurveyService.java

내가 받은 설문 단일 조회에 owner 검증 로직 추가
getSurvey에 owner 검증 로직 추가되었습니다.

내가 받은 설문 단일 조회에 owner 검증 로직 추가(#144)

---

src/main/java/com/dnd/namuiwiki/common/exception/ApplicationErrorType.java
src/main/java/com/dnd/namuiwiki/common/exception/AsyncExceptionHandler.java
src/main/java/com/dnd/namuiwiki/config/AsyncConfiguration.java
src/main/java/com/dnd/namuiwiki/config/CacheConfiguration.java
src/main/java/com/dnd/namuiwiki/config/EventConfiguration.java
src/main/java/com/dnd/namuiwiki/domain/dashboard/DashboardCustomRepository.java
src/main/java/com/dnd/namuiwiki/domain/dashboard/DashboardCustomRepositoryImpl.java
src/main/java/com/dnd/namuiwiki/domain/dashboard/DashboardRepository.java
src/main/java/com/dnd/namuiwiki/domain/dashboard/model/BestWorthDashboardComponent.java
src/main/java/com/dnd/namuiwiki/domain/dashboard/model/HappyDashboardComponent.java
src/main/java/com/dnd/namuiwiki/domain/dashboard/model/SadDashboardComponent.java
src/main/java/com/dnd/namuiwiki/domain/dashboard/model/entity/Dashboard.java
src/main/java/com/dnd/namuiwiki/domain/question/QuestionRepository.java
src/main/java/com/dnd/namuiwiki/domain/question/entity/Question.java
src/main/java/com/dnd/namuiwiki/domain/statistic/StatisticsService.java
src/main/java/com/dnd/namuiwiki/domain/survey/SurveyController.java
src/main/java/com/dnd/namuiwiki/domain/survey/SurveyEventHandler.java
src/main/java/com/dnd/namuiwiki/domain/survey/SurveyService.java
src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/SingleAnswerWithSurveyDetailDto.java
src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/SurveyCreatedEvent.java
src/main/java/com/dnd/namuiwiki/domain/survey/model/entity/Survey.java
src/test/java/com/dnd/namuiwiki/domain/statistic/StatisticsServiceTest.java
src/test/java/com/dnd/namuiwiki/domain/survey/SurveyServiceTest.java

- user, period, relation 에 대한 복합 인덱스를 생성
- 설문 생성 정상적인 동작 확인

#147 테스트 및 인덱스 생성

---

src/main/java/com/dnd/namuiwiki/domain/question/QuestionController.java
src/main/java/com/dnd/namuiwiki/domain/question/QuestionService.java
src/main/java/com/dnd/namuiwiki/domain/question/dto/QuestionDto.java

it closes #162 
이 PR은 #161 이 머지된 후 머지됩니다.
문항 조회 시 wikiType 필터 추가
- QuestionController에 wikiType 파라미터 추가되었습니다.

feat: 문항 조회 시 wikiType 필터 추가(#162)

---

src/main/java/com/dnd/namuiwiki/domain/survey/SurveyController.java
src/main/java/com/dnd/namuiwiki/domain/survey/SurveyRepository.java
src/main/java/com/dnd/namuiwiki/domain/survey/SurveyService.java
src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/ReceivedSurveyDto.java

it closes #164 
**이 PR은 #163 이 머지된 후 머지됩니다.**
내가 받은 설문 목록 조회 시 wikiType 필터 추가
- Survey Entity에 wikiType 추가(되어 있음)
- 내가 받은 설문 목록 조회에서 wikiType 필터 추가

feat: 내가 받은 설문 목록 조회 시 wikiType 필터 추가(#164)

---

src/main/java/com/dnd/namuiwiki/domain/jwt/JwtService.java
src/main/java/com/dnd/namuiwiki/domain/question/QuestionRepository.java
src/main/java/com/dnd/namuiwiki/domain/survey/SurveyRepository.java
src/main/java/com/dnd/namuiwiki/domain/survey/SurveyService.java
src/main/java/com/dnd/namuiwiki/domain/wiki/WikiController.java
src/main/java/com/dnd/namuiwiki/domain/wiki/WikiService.java
src/main/java/com/dnd/namuiwiki/domain/wiki/dto/GetWikisResponse.java
src/main/java/com/dnd/namuiwiki/domain/wiki/dto/WikiDto.java

Wiki 목록 API 구현
토큰 기반으로 사용자를 리턴하는 함수를 TokenService로 분리했습니다.
WikiType을 Enum으로 관리하다보니 중복 코드가 좀 생긴 것 같아서 조금 후회를 하긴 했지만.. 우선은 괜찮을 것 같습니다

feat: Wiki 목록 API 구현(#158)

---

src/main/java/com/dnd/namuiwiki/domain/jwt/JwtService.java
src/main/java/com/dnd/namuiwiki/domain/question/QuestionRepository.java
src/main/java/com/dnd/namuiwiki/domain/survey/SurveyRepository.java
src/main/java/com/dnd/namuiwiki/domain/survey/SurveyService.java
src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/GetSurveyResponse.java
src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/SentSurveyDto.java
src/main/java/com/dnd/namuiwiki/domain/wiki/WikiController.java
src/main/java/com/dnd/namuiwiki/domain/wiki/WikiService.java
src/main/java/com/dnd/namuiwiki/domain/wiki/dto/GetWikisResponse.java
src/main/java/com/dnd/namuiwiki/domain/wiki/dto/WikiDto.java

작성한 설문 목록 조회, 설문 상세 조회 API 응답 WikiType 추가

작성한 설문 목록 조회, 설문 상세 조회 API 응답 WikiType 추가

---

src/main/java/com/dnd/namuiwiki/domain/option/dto/OptionDto.java
src/main/java/com/dnd/namuiwiki/domain/question/dto/QuestionDto.java

feat: 질문 조회 시 응답에 옵션 Description 추가(#175)
- OptionDto에 description 필드 추가
너무나 간단한 사항이라 바로 머지하겠습니다!

feat: 질문 조회 시 응답에 옵션 Description 추가(#175)

---

src/main/java/com/dnd/namuiwiki/domain/dashboard/DashboardCustomRepositoryImpl.java
src/main/java/com/dnd/namuiwiki/domain/dashboard/model/RankDashboardComponent.java
src/main/java/com/dnd/namuiwiki/domain/dashboard/model/dto/RankDto.java
src/main/java/com/dnd/namuiwiki/domain/statistic/model/Rank.java
src/main/java/com/dnd/namuiwiki/domain/statistic/model/RankStatistic.java

feat: rank dashboard update 구현

---

src/main/java/com/dnd/namuiwiki/domain/survey/AnswerController.java
src/main/java/com/dnd/namuiwiki/domain/survey/SurveyRepository.java
src/main/java/com/dnd/namuiwiki/domain/survey/SurveyService.java

feat: 질문별 답변 조회 API 필터 조건에 wikiType 추가

---

src/main/java/com/dnd/namuiwiki/common/util/ListUtils.java
src/main/java/com/dnd/namuiwiki/domain/question/entity/Question.java
src/main/java/com/dnd/namuiwiki/domain/question/type/QuestionType.java
src/main/java/com/dnd/namuiwiki/domain/statistic/model/AverageStatistic.java
src/main/java/com/dnd/namuiwiki/domain/statistic/model/RatioStatistic.java
src/main/java/com/dnd/namuiwiki/domain/survey/SurveyService.java
src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/GetSurveyResponse.java
src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/SimpleAnswerDto.java
src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/SingleAnswerWithSurveyDetailDto.java
src/main/java/com/dnd/namuiwiki/domain/survey/model/entity/Answer.java

답변 조회 응답 값 수정
- 답변을 조회하는 API(질문 별 답변, 대시보드 답변)에서 응답 값 수정
- 기존 `value`, `text`를 `Object answer`로 통합
- RANK 타입일 경우 `List<SimpleAnswerDto>` 이고, 나머지는 `SimpleAnswerDto`

RANK 타입 대시보드 응답 타입 수정

---

src/main/java/com/dnd/namuiwiki/domain/survey/SurveyService.java
src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/GetAnswersByQuestionResponse.java

fix: 질문별 답변 API 응답에 question type 추가

---

src/main/java/com/dnd/namuiwiki/domain/dashboard/model/BinaryDashboardComponent.java
src/main/java/com/dnd/namuiwiki/domain/dashboard/model/RatioDashboardComponent.java
src/main/java/com/dnd/namuiwiki/domain/statistic/model/Legend.java
src/main/java/com/dnd/namuiwiki/domain/statistic/model/RatioStatistic.java

fix: legend에서 option text, value 삭제
